udong-frontend/app/ui/feature/club/event/EventContainer.tsx
udong-frontend/app/ui/feature/club/event/calendar/EventCalendar.tsx
udong-frontend/app/ui/feature/club/event/calendar/EventCalendarView.tsx
udong-frontend/app/ui/feature/club/post/PostContainer.tsx
udong-frontend/app/ui/feature/club/post/PostContentView.tsx
udong-frontend/app/ui/feature/club/post/PostCreateContainer.tsx
udong-frontend/app/ui/feature/home/HomeContainer.tsx
udong-frontend/app/ui/feature/home/feed/FeedContainer.tsx
udong-frontend/app/ui/feature/home/mydong/MyDongContainer.tsx
udong-frontend/app/ui/feature/shared/TimeTable.tsx
udong-frontend/pages/club/[clubId].tsx
udong-frontend/pages/club/[clubId]/post/create.tsx

지연: 
* `http://localhost:3000/club/1` (아직 탭 작업 안 돼서 그냥 club page에서 해주시면 제가 나중에 알아서 리팩토링 + 분리하겠습니당)
* `feature/club/event` 안에서 모든 작업! (subcomponent 만들때 다 여기에 만들어주세요)
* `EventView`는 웬만하면 코드 작업 X (탭 관련 로직 들어가는데 제가 할 예정)
* `EventCalendarView`가 모든 캘린더 작업의 최상위 parent라고 생각하면 됨, 캘린더 + 날짜 없는 행사 들어가는 영역
* `EventCalendar`가 캘린더만!! 여기 작업해주면 될듯
동현
* `http://localhost:3000/club/1/post/create`
* `feature/club/post` 안에서 모든 작업! (subcomponent 혹시 더 필요하면 만들때 그냥 다 여기서 만들어도 될듯)
* `PostCreateContainer`는 input하는거 말고도 다른거 들어갈 수 있음, 여기는 작업 X
* `PostContentView`가 찐으로 외부 라이브러리 들어갈 곳, 여기 작업해주면 됨!
유진:
* `feature/shared` 안에 `TimeTable`이라는 컴포넌트 만들었는데 자유롭게 써주면 될듯
* subcomponent 필요하면 이 또한 자유롭게 만들어줄 수 있으며 똑같은 디렉토리에서 만들면 될듯!
* 아직 페이지 안 만들었으니 `http://localhost:3000/dummy`에서 테스트해주시면 감사하겠습니다.

🗂️  코드 작업 나누기

---

.github/workflows/Backend-CI.yml

Backend CI 구현
- format files by black
- type check by mypy

:white_check_mark: back/feat/CI

---

udong-backend/README.md

:hammer: Fix README.md

---

.github/workflows/SonarCloud.yml
README.md
sonar-project.properties

:technologist: Sonarcloud

---

udong-backend/requirements.txt
udong-backend/udong/udong/settings.py
udong-backend/udong/udong/urls.py

:bulb: Back/feat/django-debug-toolbar

---

udong-frontend/app/ui/feature/shared/DraggableTimeTable.tsx
udong-frontend/pages/dummy/index.tsx

http://localhost:3000/dummy 에서 확인 가능

Implement DraggableTimeTable.tsx

---

.github/workflows/Backend-CI.yml
.github/workflows/frontend-eslint-pr.yml

:hammer: Make check status on PR

---

udong-backend/udong/Makefile
udong-backend/udong/club/serializers.py
udong-backend/udong/club/urls.py
udong-backend/udong/club/views.py
udong-backend/udong/dummy.py
udong-backend/udong/udong/urls.py
udong-backend/udong/user/models.py
udong-backend/udong/user/serializers.py
udong-backend/udong/user/urls.py
udong-backend/udong/user/views.py

- api/user/me
- api/user/:id
- api/club/
까지 구현 완료

:man: Back/feat/get user

---

udong-backend/udong/club/serializers.py
udong-backend/udong/event/serializers.py
udong-backend/udong/user/serializers.py

created_at, updated_at 전부 read_only로 바꿈

:wrench: Make created_at & updated_at read_only

---

udong-frontend/app/ui/feature/club/post/upsert/PostInputView.tsx
udong-frontend/app/ui/feature/club/post/upsert/create/PostCreateContainer.tsx
udong-frontend/app/ui/feature/club/post/upsert/edit/PostEditContainer.tsx

게시글 생성 / 수정페이지에서 제목 입력 가능하게 해놓았습니다.

:wrench: Front/fix/title input

---

udong-frontend/app/ui/feature/club/board/BoardContainer.tsx
udong-frontend/app/ui/feature/home/feed/FeedContainer.tsx

* 피드와 게시판에 fake loading 0.6초씩 넣었습니다

🟢  Front/feat/fake loading

---

udong-frontend/app/ui/components/UdongRadioButton.tsx
udong-frontend/app/ui/feature/club/board/BoardContainer.tsx
udong-frontend/app/ui/feature/club/board/PostCreateModal.tsx
udong-frontend/app/ui/feature/club/post/detail/PostDetailContainer.tsx
udong-frontend/app/ui/feature/club/post/upsert/AdditionalFieldItem.tsx
udong-frontend/app/ui/feature/club/post/upsert/PostAdditionalFieldsView.tsx
udong-frontend/app/ui/feature/club/post/upsert/create/PostCreateContainer.tsx
udong-frontend/app/ui/feature/club/post/upsert/edit/PostEditContainer.tsx
udong-frontend/app/ui/feature/home/HomeContainer.tsx
udong-frontend/app/ui/feature/shared/DeleteModal.tsx
udong-frontend/pages/club/[clubId]/post/[postId]/edit.tsx
udong-frontend/pages/club/[clubId]/post/create.tsx

- 게시글 생성할 때 어떤 타입으로 생성할지 물어보는 모달 띄워주기
- 타입에 따라 post create 그려주기
- 타입에 따라 post edit 그려주기

🍋 feat: choose post type (create & edit)

---

udong-frontend/app/ui/components/UdongButton.tsx
udong-frontend/app/ui/components/UdongChip.tsx
udong-frontend/app/ui/components/UdongHeader.tsx
udong-frontend/app/ui/components/UdongImage.tsx
udong-frontend/app/ui/feature/club/tag/TagItem.tsx
udong-frontend/app/ui/feature/club/tag/TagUpsertModal.tsx
udong-frontend/app/ui/feature/header/Header.tsx
udong-frontend/app/ui/feature/home/mydong/AddClubModal.tsx
udong-frontend/app/ui/feature/home/mydong/CloseModalButton.tsx
udong-frontend/app/ui/feature/home/mydong/ClubItem.tsx
udong-frontend/app/ui/feature/home/mydong/MyDongContainer.tsx
udong-frontend/app/ui/feature/shared/ClickableTag.tsx
udong-frontend/app/ui/feature/shared/UserItem.tsx

- UdongButton hover시 색깔 바뀜 + 커서 모양 바뀜
- 기타 클릭 가능한 컴포넌트들 호버시 커서 모양 바뀜

:art: Front/feat/button mouse

---

udong-frontend/app/ui/feature/club/post/detail/PostDetailSchedulingView.tsx
udong-frontend/app/ui/feature/mypage/AddMyScheduleView.tsx
udong-frontend/app/ui/theme/ColorPalette.ts

- UdongColors.Primary50 추가
- UdongColors.Primary에 opacity 50%를 준 것과 비슷
- MyProfile과 PostDetail에 반영

:lipstick: Change color of TimeTable

---

udong-frontend/app/ui/components/UdongTab.tsx
udong-frontend/app/ui/components/UdongText.tsx
udong-frontend/app/ui/feature/club/ClubContainer.tsx

:timer_clock: Front/fix/tab view

---

udong-frontend/app/ui/components/UdongChip.tsx
udong-frontend/app/ui/feature/club/post/detail/PostDetailContainer.tsx
udong-frontend/app/ui/feature/club/post/scheduling/SchedulingCloseContainer.tsx
udong-frontend/app/ui/feature/club/post/scheduling/SchedulingStatusContainer.tsx
udong-frontend/app/ui/feature/club/post/scheduling/SchedulingUserListView.tsx
udong-frontend/app/ui/feature/club/post/upsert/PostAdditionalFieldsView.tsx
udong-frontend/app/ui/feature/club/tag/TagItem.tsx
udong-frontend/app/ui/feature/shared/ClickableTag.tsx
udong-frontend/app/ui/feature/shared/ProfileView.tsx
udong-frontend/app/ui/feature/shared/UserItem.tsx
udong-frontend/pages/dummy/index.tsx

- `style`만 받던 것을 `color`와 `style`로 나눔
- UdongChip을 이용한 component들 이에 맞춰 수정함
- SchedulingUserListView에서 UdongChip 색깔이 제대로 안 나오던 것 해결
- http://localhost:3000/club/1/post/1/status
- http://localhost:3000/club/1/post/1/close

:lipstick: Change UdongChip props

---

udong-frontend/app/ui/feature/club/ClubContainer.tsx
udong-frontend/app/ui/feature/header/Header.tsx

- 상단 더미 동아리 이름 단풍으로 바꿈
- 흔들리는 현상 다시 fix

:wrench: Front/fix/tab view3

---

udong-frontend/app/domain/model/Club.ts
udong-frontend/app/domain/model/Event.ts
udong-frontend/app/domain/model/Post.ts
udong-frontend/app/domain/model/PostType.ts
udong-frontend/app/domain/model/Tag.ts
udong-frontend/app/domain/model/User.ts
udong-frontend/app/ui/feature/club/board/BoardContainer.tsx
udong-frontend/app/ui/feature/club/event/detail/EventDetailContainer.tsx
udong-frontend/app/ui/feature/club/post/detail/PostDetailContainer.tsx
udong-frontend/app/ui/feature/home/feed/FeedContainer.tsx
udong-frontend/app/ui/feature/shared/PostItem.tsx
udong-frontend/app/utility/postItemFormatter.tsx

* PostItem이 사용되는 모든 곳에 dummy data를 넣어주고 이를 적절하게 그려줍니다.
* PostDetail에서는 queryParam으로 select된 게시글의 PostType을 넘겨 받아 그에 따라 UI를 다르게 그려줍니다.

🥟 feat: post dummy data

---

udong-frontend/app/ui/feature/shared/ScrollToTopButton.tsx

:sparkles: Hide ScrollToTopButton when scrolled

---

udong-frontend/app/ui/feature/club/post/upsert/PostInputView.tsx

:hammer: Fix Quill Loader

---

udong-frontend/app/ui/feature/club/tag/TagContainer.tsx
udong-frontend/app/ui/feature/shared/UserListModal.tsx

:wrench: Fix Tag's dummy data

---

udong-frontend/pages/__tests__/mypage.test.tsx
udong-frontend/tests/tsconfig.json
udong-frontend/tests/unit/index.test.tsx

:white_check_mark: Implement mypage.test.tsx

---

udong-frontend/jest.config.js

이제 `yarn run test`하면 coverage 폴더 안의 index.html이 만들어집니다~

Export coverage as html by jest

---

udong-backend/requirements.txt
udong-backend/udong/common/utils.py

- jsonEqual 함수 정의
- test 시 MyTestCase 상속하여 사용

:toolbox: Back/test/common

---

udong-frontend/app/ui/components/UdongTab.tsx

:wrench: Fix transition

---

README.md

관련 이슈: https://github.com/swsnu/swppfall2022/issues/184

Kill cache for coverage badge

---

udong-backend/udong/club/serializers.py

- api/club/:id/event/ 에 id field 추가
- api/club/:id/tag/ 에 id field 추가

:hammer_and_pick: Add id field

---

udong-frontend/package.json

`yarn run test --coverage --watchAll=false` 돌리던 것을 그냥 `yarn run test`만 돌리면 되게 수정

:technologist: Update script "yarn run test"

---

udong-backend/udong/post/serializers.py

api/post/club/:id/ 에 post의 id도 추가로 return

:hammer_and_wrench: Add id field

---

udong-backend/udong/user/models.py

User에 time_table field 추가하면서 dummy user에 추가하는걸 까먹은 버그 수정

:man: Fix dummy user

---

udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingCloseContainer.test.tsx
udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingCloseModal.test.tsx
udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingHooks.test.ts
udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingStatusContainer.test.tsx
udong-frontend/app/ui/feature/club/post/scheduling/__tests__/SchedulingStatusTableView.test.tsx

:white_check_mark: Test scheduling

---

sonar-project.properties
udong-frontend/jest.config.js

:wrench: Exclude pages folder from coverage target

---

udong-frontend/app/ui/feature/club/post/upsert/PostInputView.tsx
udong-frontend/app/ui/feature/club/post/upsert/__test__/AdditionalFieldItem.test.tsx
udong-frontend/app/ui/feature/club/post/upsert/__test__/PostAdditionalFieldsView.test.tsx
udong-frontend/app/ui/feature/club/post/upsert/__test__/PostDateSchedule.test.tsx
udong-frontend/app/ui/feature/club/post/upsert/__test__/PostDaySchedule.test.tsx
udong-frontend/app/ui/feature/club/post/upsert/__test__/PostInputView.test.tsx

:postbox: Front/test/post upsert

---

README.md

:scroll: Readme

---

udong-frontend/app/domain/store/auth/AuthSelector.ts
udong-frontend/app/domain/store/auth/AuthSlice.ts
udong-frontend/app/domain/store/club/ClubSelector.ts
udong-frontend/app/domain/store/club/ClubSlice.ts
udong-frontend/app/domain/store/comment/CommentSelector.ts
udong-frontend/app/domain/store/comment/CommentSlice.ts
udong-frontend/app/domain/store/event/EventSelector.ts
udong-frontend/app/domain/store/event/EventSlice.ts
udong-frontend/app/domain/store/index.ts
udong-frontend/app/domain/store/post/PostSelector.ts
udong-frontend/app/domain/store/post/PostSlice.ts
udong-frontend/app/domain/store/post/enrollment/EnrollmentSelector.ts
udong-frontend/app/domain/store/post/enrollment/EnrollmentSlice.ts
udong-frontend/app/domain/store/post/scheduling/SchedulingSelector.ts
udong-frontend/app/domain/store/post/scheduling/SchedulingSlice.ts
udong-frontend/app/domain/store/tag/TagSelector.ts
udong-frontend/app/domain/store/tag/TagSlice.ts
udong-frontend/app/domain/store/user/UserSelector.ts
udong-frontend/app/domain/store/user/UserSlice.ts
udong-frontend/app/infra/api/AuthAPI.ts
udong-frontend/app/infra/api/ClubAPI.ts
udong-frontend/app/infra/api/CommentAPI.ts
udong-frontend/app/infra/api/EnrollmentAPI.ts
udong-frontend/app/infra/api/EventAPI.ts
udong-frontend/app/infra/api/PostAPI.ts
udong-frontend/app/infra/api/SchedulingAPI.ts
udong-frontend/app/infra/api/TagAPI.ts
udong-frontend/app/infra/api/UserAPI.ts
udong-frontend/package.json
udong-frontend/yarn.lock

대략 설명을 하자면,
`domain/store`
- 여기서는 state 관리, action 정의
- axios X
`infra/api`
- axios O
- 여기서 직접 백엔드 api 호출

⚙️ feat: setup redux

---

udong-backend/udong/comment/views.py

serializer.update를 직접 부르는게 거슬려서 바꿨어요

:adhesive_bandage: Do not call serializer.update directly

---

udong-backend/requirements.txt
udong-backend/udong/club/views.py
udong-backend/udong/comment/views.py
udong-backend/udong/post/views.py
udong-backend/udong/user/views.py

- stubs package update 했습니다.
- drf stub이 update 되어서 generic 관련 issue 수정했습니다.

:up: Update stubs

---

.github/workflows/test-coverage.yml
README.md

https://github.com/swsnu/swppfall2022/issues/184#issuecomment-1312702123 참고

:construction_worker: Send purge requeset

---

udong-frontend/app/domain/model/Tag.ts
udong-frontend/app/infra/transformer/BoardPostTransformer.ts
udong-frontend/app/infra/transformer/PostTagTransformer.ts

🩹 fix: create post tag transformer

---

udong-backend/udong/post/views.py

:post_office: Back/feat/get-post2

---

udong-backend/udong/udong/urls.py

:globe_with_meridians: Enable swagger in production

---

udong-backend/udong/udong/settings.py

:art: Set static files

---

udong-backend/udong/udong/urls.py
udong-backend/udong/udong/views.py

:ping_pong: Set ping api

---

udong-backend/udong/udong/views.py

ping api get으로만 가능하게 해서 csrf warning 해소

:ping_pong: Fix csrf warning

---

udong-backend/udong/user/views.py

- logout 구현
- Dummyuser 관련은 추후 pr에서 구현 예정

:man_artist: Implement logout

---

udong-backend/udong/club/tests.py
udong-backend/udong/post/tests.py
udong-backend/udong/user/tests.py

:man_astronaut: Back/test/auth

---

udong-backend/udong/udong/urls.py

:x: Ban admin/ if debug is false

---

udong-backend/udong/comment/serializers.py

:wrench: Back/fix/commentserializer

---

udong-backend/udong/user/views.py

- user put, delete 구현
- user가 하나 이상의 동아리의 관리자일 경우 삭제 막음

:man_astronaut: Back/feat/api user

---

udong-backend/udong/event/serializers.py
udong-backend/udong/post/serializers.py
udong-backend/udong/post/tests.py

:balloon: Back/fix/postdetailevent

---

udong-backend/udong/post/serializers.py
udong-backend/udong/post/tests.py
udong-backend/udong/post/views.py

post return 할때 author도 같이 return 함

:man_artist: Back/fix/postdetailauthor

---

udong-frontend/app/domain/model/User.ts
udong-frontend/app/domain/store/__test__/UserSlice.test.ts
udong-frontend/app/infra/transformer/UserTransformer.ts
udong-frontend/app/ui/feature/mypage/AddMyScheduleView.tsx
udong-frontend/app/ui/feature/mypage/MyPageContainer.tsx
udong-frontend/app/ui/feature/mypage/__test__/AddMyScheduleView.test.tsx
udong-frontend/app/ui/feature/shared/DraggableTimeTable.tsx
udong-frontend/app/utility/timetableFormatter.ts

:sparkles: Implement handleEditTimeTable

---

udong-backend/udong/club/serializers.py
udong-backend/udong/club/views.py
udong-backend/udong/common/permissions.py

- club 생성, 정보 수정, club 삭제 구현
- Permission에 관리자인지 체크하는 로직 구현 (필요하면 쓰세요)

:clubs: Back/feat/api-club

---

udong-backend/udong/club/serializers.py
udong-backend/udong/club/views.py

:hammer_and_wrench: Back/fix/club register

---

udong-backend/udong/club/views.py

:mechanic: Add club/id/user/me api

---

udong-frontend/app/domain/store/comment/CommentSlice.ts
udong-frontend/app/domain/store/tag/TagSlice.ts

애초에 남의 코멘트를 delete 못하지만.. (버튼이 안 떠서..) 그냥 해봤어요..

🥅 fix: comment deletion error handling

---

udong-backend/udong/club/views.py

register하면 club return 하게 바꿨습니다

:clubs: Set Return value to register api

---

udong-frontend/app/domain/model/Club.ts
udong-frontend/app/domain/store/club/ClubSelector.ts
udong-frontend/app/domain/store/club/ClubSlice.ts
udong-frontend/app/infra/api/ClubAPI.ts
udong-frontend/app/infra/api/UserAPI.ts
udong-frontend/app/infra/dto/ClubDto.ts
udong-frontend/app/infra/transformer/ClubTransformer.ts
udong-frontend/app/ui/components/UdongCloseButton.tsx
udong-frontend/app/ui/components/UdongErrorModal.tsx
udong-frontend/app/ui/components/UdongTextField.tsx
udong-frontend/app/ui/feature/club/post/scheduling/SchedulingCloseModal.tsx
udong-frontend/app/ui/feature/home/mydong/CreateClubModal.tsx
udong-frontend/app/ui/feature/home/mydong/RegisterClubModal.tsx
udong-frontend/app/ui/feature/home/mydong/__test__/CloseModalButton.test.tsx
udong-frontend/app/ui/feature/home/mydong/__test__/RegisterClubModal.test.tsx
udong-frontend/app/ui/feature/shared/DeleteModal.tsx

✨ feat: club register

---

udong-backend/udong/club/serializers.py

:framed_picture: Set default value of club image

---

udong-frontend/app/domain/model/PostType.ts
udong-frontend/app/domain/store/club/ClubSlice.ts
udong-frontend/app/domain/store/post/scheduling/SchedulingSlice.ts
udong-frontend/app/infra/api/SchedulingAPI.ts
udong-frontend/app/ui/components/UdongButton.tsx
udong-frontend/app/ui/feature/club/board/__test__/PostCreateModal.test.tsx
udong-frontend/app/ui/feature/club/post/scheduling/SchedulingCloseContainer.tsx
udong-frontend/app/ui/feature/club/post/scheduling/SchedulingCloseModal.tsx
udong-frontend/app/ui/feature/club/post/scheduling/SchedulingHooks.ts
udong-frontend/app/ui/feature/club/post/scheduling/SchedulingStatusContainer.tsx
udong-frontend/app/ui/feature/club/post/scheduling/__test__/SchedulingCloseContainer.test.tsx
udong-frontend/app/ui/feature/club/post/scheduling/__test__/SchedulingCloseModal.test.tsx
udong-frontend/app/ui/feature/club/post/scheduling/__test__/SchedulingStatusContainer.test.tsx

`POST /club/:id/event/`랑 `PUT /event/:id/`는 백엔드 구현이 안돼있어서 연결 못함

:sparkles: Front/feat/close scheduling

---

udong-backend/udong/club/serializers.py
udong-backend/udong/common/random.py

sonarcloud에서 random 안전하지 않다고 한거 고쳤습니다

:game_die: Back/feat/random code

---

udong-backend/udong/comment/views.py
udong-backend/udong/common/permissions.py
udong-backend/udong/dummy.py
udong-backend/udong/post/views.py

- 댓글 수정의 경우 원 작성자만 수정할 수 있는 IsAuthor Permission 추가
- post, enrollment, scheduling을 볼 수 있는 CanRead  Permission 추가

:lock: Back/feat/permissions

---

udong-backend/udong/club/tests.py
udong-backend/udong/club/views.py

:clubs: Back/test/club2

---

udong-frontend/app/domain/store/__test__/PostSlice.test.ts
udong-frontend/app/domain/store/__test__/TagSlice.test.ts
udong-frontend/app/domain/store/post/PostSelector.ts
udong-frontend/app/domain/store/post/PostSlice.ts
udong-frontend/app/domain/store/tag/TagSelector.ts
udong-frontend/app/domain/store/tag/TagSlice.ts
udong-frontend/app/ui/feature/club/__test__/ClubContainer.test.tsx
udong-frontend/app/ui/feature/club/board/__test__/BoardContainer.test.tsx
udong-frontend/app/ui/feature/club/post/detail/__test__/PostDetailContainer.test.tsx
udong-frontend/app/ui/feature/club/post/scheduling/__test__/SchedulingCloseContainer.test.tsx
udong-frontend/app/ui/feature/club/post/upsert/PostAdditionalFieldsView.tsx
udong-frontend/app/ui/feature/club/post/upsert/PostAdditionalInputsView.tsx
udong-frontend/app/ui/feature/club/post/upsert/TagListModal.tsx
udong-frontend/app/ui/feature/club/post/upsert/__test__/PostAdditionalFieldsView.test.tsx
udong-frontend/app/ui/feature/club/post/upsert/create/PostCreateContainer.tsx
udong-frontend/app/ui/feature/club/post/upsert/create/__test__/PostCreateContainer.test.tsx
udong-frontend/app/ui/feature/club/tag/__test__/TagContainer.test.tsx
udong-frontend/app/ui/feature/home/__test__/HomeContainer.test.tsx
udong-frontend/app/ui/feature/home/feed/__test__/FeedContainer.test.tsx
udong-frontend/app/ui/feature/shared/__test__/PostItem.test.tsx

포스트 생성 시에 디폴트로 전체 태그 추가된 상태 + refactor

🎨 fix: post create default tag

---

udong-backend/udong/club/tests.py
udong-backend/udong/tag/serializers.py
udong-frontend/app/infra/api/ClubAPI.ts

Fix POST /club/:id/tag/

---

udong-backend/udong/club/views.py

:man_technologist: Add club/id/code api

---

udong-frontend/app/ui/feature/club/event/list/EventItem.tsx
udong-frontend/app/ui/feature/club/post/detail/PostDetailContainer.tsx
udong-frontend/app/ui/feature/club/tag/TagItem.tsx
udong-frontend/app/ui/feature/shared/PostItem.tsx
udong-frontend/app/utility/dateTimeFormatter.ts

- 시간 format 구현 완료했습니다
- verbose가 true이면 ~시간전 이런 형식 지원하고, 아니면 날짜 형식으로 출력

:hourglass: Front/feat/format time

---

udong-frontend/app/ui/feature/club/post/detail/PostDetailSchedulingView.tsx
udong-frontend/app/ui/feature/club/post/scheduling/SchedulingHooks.ts

- 이전에 제출한 나의 일정 받아와서 자동으로 보여줌
- 관리자에게만 "마감하기" 버튼 보임
- "일정 제출하기" 클릭 시 토스트 뜸

:sparkles: Update PostDetailSchedulingView

---

udong-backend/udong/club/views.py

:label: Back/feat/default tag delete

---

udong-backend/udong/post/views.py
udong-backend/udong/tag/views.py

:mechanical_arm: Back/feat/enrollment me

---

udong-frontend/app/domain/store/club/ClubSlice.ts
udong-frontend/app/infra/api/ClubAPI.ts
udong-frontend/app/ui/feature/club/info/ClubProfileView.tsx
udong-frontend/app/ui/feature/club/info/InfoContainer.tsx
udong-frontend/app/ui/feature/shared/ProfileView.tsx

:new: Implement refresh code

---

udong-frontend/app/domain/model/Participation.ts
udong-frontend/app/domain/store/post/enrollment/EnrollmentSelector.ts
udong-frontend/app/domain/store/post/enrollment/EnrollmentSlice.ts
udong-frontend/app/infra/api/EnrollmentAPI.ts
udong-frontend/app/infra/dto/ParticipationDto.ts
udong-frontend/app/infra/transformer/ParticipationTransformer.ts
udong-frontend/app/ui/feature/club/post/detail/PostDetailEnrollmentView.tsx

enrollment post detail에서 유저의 partcipation 상태를 확인합니다

✨ feat: is user enrolled API

---

udong-frontend/app/ui/feature/club/info/ClubProfileView.tsx
udong-frontend/app/ui/feature/club/info/__test__/ClubProfileView.test.tsx
udong-frontend/app/ui/feature/club/info/__test__/InfoContainer.test.tsx
udong-frontend/app/ui/feature/shared/ProfileView.tsx

:framed_picture: Get club image from s3

---

udong-frontend/app/ui/feature/club/info/ClubProfileView.tsx
udong-frontend/app/ui/feature/shared/LeaveModal.tsx

✨ feat: 동아리 탈퇴 모달

---

udong-backend/udong/image/views.py
udong-frontend/app/domain/model/Image.ts
udong-frontend/app/domain/store/club/ClubSlice.ts
udong-frontend/app/infra/api/ImageAPI.ts
udong-frontend/app/infra/dto/ImageDto.ts
udong-frontend/app/infra/transformer/ImageTransformer.ts
udong-frontend/app/ui/feature/club/info/ClubMemberProfileView.tsx
udong-frontend/app/ui/feature/club/info/ClubProfileView.tsx
udong-frontend/app/ui/feature/mypage/MyProfileView.tsx
udong-frontend/app/ui/feature/shared/ProfileView.tsx
udong-frontend/docker.sh

:framed_picture: Front/feat/image upload

---

udong-frontend/app/ui/feature/club/post/upsert/create/PostCreateContainer.tsx

🐛 fix: post create set default tag

---

udong-frontend/app/ui/feature/club/post/upsert/PostInputView.tsx

:movie_camera: Delete image, video tab in quill
